capp/carbon_app/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, FloatField
from wtforms.validators import InputRequired

###############################
###   App Calculator form   ###
###############################
class AddRecordForm(FlaskForm):
    bus_kms = FloatField("Bus (Kilometers)", [InputRequired()])
    bus_co2 = FloatField("Bus (CO2)")
    bus_type = SelectField("Bus (Type of Fuel)",
                           [InputRequired()],
                           choices=[
                               ('Bus Diesel', 'Bus Diesel'),
                               ('Bus CNG', 'Bus CNG'),
                               ('Bus Petrol', 'Bus Petrol'),
                               ('Bus No Fossil Fuel', 'Bus No Fossil Fuel')
                           ])
    car_kms = FloatField("Car (Kilometers)", [InputRequired()])
    car_co2 = FloatField("Car (CO2)")
    car_type = SelectField("Car (Type of Fuel)",
                           [InputRequired()],
                           choices=[
                               ('Car Petrol', 'Car Petrol'),
                               ('Car Diesel', 'Car Diesel'),
                               ('Car No Fossil Fuel', 'Car No Fossil Fuel')
                           ])
    plane_kms = FloatField("Plane (Kilometers)", [InputRequired()])
    plane_co2 = FloatField("Plane (CO2)")
    plane_type = SelectField("Plane (Type of Fuel)",
                           [InputRequired()],
                           choices=[
                               ('Plane Jet Fuel', 'Plane Jet Fuel'),
                               ('Plane No Fossil Fuel', 'Plane No Fossil Fuel')
                           ])
    ferry_kms = FloatField("Ferry (Kilometers)", [InputRequired()])
    ferry_co2 = FloatField("Ferry (CO2)")
    ferry_type = SelectField("Ferry (Type of Fuel)",
                             [InputRequired()],
                             choices=[
                                 ('Ferry Diesel', 'Ferry Diesel'),
                                 ('Ferry No Fossil Fuel', 'Ferry No Fossil Fuel')
                             ])
    motorbike_kms = FloatField("Motorbike (Kilometers)", [InputRequired()])
    motorbike_co2 = FloatField("Motorbike (CO2)")
    motorbike_type = SelectField("Motorbike (Type of Fuel)",
                             [InputRequired()],
                             choices=[
                                 ('Motorbike Petrol', 'Motorbike Petrol'),
                                 ('Motorbike No Fossil Fuel', 'Motorbike No Fossil Fuel')
                             ])
    scooter_kms = FloatField("Scooter (Kilometers)", [InputRequired()])
    scooter_co2 = FloatField("Scooter (CO2)")
    scooter_type = SelectField("Scooter (Type of Fuel)",
                                 [InputRequired()],
                                 choices=[
                                     ('Scooter No Fossil Fuel', 'Scooter No Fossil Fuel')
                                 ])
    bicycle_kms = FloatField("Bicycle (Kilometers)", [InputRequired()])
    bicycle_co2 = FloatField("Bicycle (CO2)")
    bicycle_type = SelectField("Bicycle (Type of Fuel)",
                               [InputRequired()],
                               choices=[
                                   ('Bicycle No Fossil Fuel', 'Bicycle No Fossil Fuel')
                               ])
    walk_kms = FloatField("Walk (Kilometers)", [InputRequired()])
    walk_co2 = FloatField("Walk (CO2)")
    walk_type = SelectField("Walk (Type of Fuel)",
                               [InputRequired()],
                               choices=[
                                   ('Walk No Fossil Fuel', 'Walk No Fossil Fuel')
                               ])
    submit = SubmitField("Submit")

capp/__init__.py
from flask import Flask
import os

application = Flask(__name__)

# application.config['SECRET_KEY'] = os.environ['SECRET_KEY']  

application.config['SECRET_KEY'] = 'adddd7987d5400199c650f5de1393135908d2605a8b67824'

from capp.home.routes import home
from capp.methodology.routes import methodology
from capp.carbon_app.routes import carbon_app 


application.register_blueprint(home)
application.register_blueprint(methodology)
application.register_blueprint(carbon_app)

capp/carbon_app/routes.py
from flask import render_template, Blueprint
from capp.carbon_app.forms import AddRecordForm
from capp.carbon_app.carbon_calculator_functions import co2_bus_calculator, co2_car_calculator, co2_plane_calculator, co2_ferry_calculator, co2_motorbike_calculator

carbon_app=Blueprint('carbon_app',__name__)

@carbon_app.route('/carbon_app', methods=['GET', 'POST'])
def carbon_app_home():
    form = AddRecordForm()
    if form.validate_on_submit():
        bus_kms = form.bus_kms.data
        car_kms = form.car_kms.data
        plane_kms = form.plane_kms.data
        ferry_kms = form.ferry_kms.data
        motorbike_kms = form.motorbike_kms.data
        scooter_kms = form.scooter_kms.data
        bicycle_kms = form.bicycle_kms.data
        walk_kms = form.walk_kms.data

        bus_type = form.bus_type.data
        car_type = form.car_type.data
        plane_type = form.plane_type.data
        ferry_type = form.ferry_type.data
        motorbike_type = form.motorbike_type.data
        scooter_type = form.scooter_type.data
        bicycle_type = form.bicycle_type.data
        walk_type = form.walk_type.data

        co2_bus = co2_bus_calculator(bus_type, bus_kms)
        co2_car = co2_car_calculator(car_type, car_kms)
        co2_plane = co2_plane_calculator(plane_type, plane_kms)
        co2_ferry = co2_ferry_calculator(ferry_type, ferry_kms)
        co2_motorbike = co2_motorbike_calculator(motorbike_type, motorbike_kms)
        co2_scooter = float(scooter_kms) * 0
        co2_bicycle = float(bicycle_kms) * 0
        co2_walk = float(walk_kms) * 0

        co2_bus = float("{:.2f}".format(co2_bus))
        co2_car = float("{:.2f}".format(co2_car))
        co2_plane = float("{:.2f}".format(co2_plane))
        co2_ferry = float("{:.2f}".format(co2_ferry))
        co2_motorbike = float("{:.2f}".format(co2_motorbike))
        co2_scooter = float("{:.2f}".format(co2_scooter))
        co2_bicycle = float("{:.2f}".format(co2_bicycle))
        co2_walk = float("{:.2f}".format(co2_walk))

        form.bus_co2.data = co2_bus
        form.car_co2.data = co2_car
        form.plane_co2.data = co2_plane
        form.ferry_co2.data = co2_ferry
        form.motorbike_co2.data = co2_motorbike
        form.scooter_co2.data = co2_scooter
        form.bicycle_co2.data = co2_bicycle
        form.walk_co2.data = co2_walk
        return render_template('carbon_app/carbon_app2.html', title='App Calculator', legend='App Calculator', form=form, 
            co2_bus=co2_bus, co2_car=co2_car, co2_plane=co2_plane, co2_ferry=co2_ferry, co2_motorbike=co2_motorbike,
            co2_scooter=co2_scooter, co2_bicycle=co2_bicycle, co2_walk=co2_walk)
    return render_template('carbon_app/carbon_app.html', title='App Calculator', legend='App Calculator', form=form)

    

capp/home/routes.py
from flask import render_template, Blueprint

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/templates/home.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->

<section class="section_header_home">
  <div class="container">

    <div class="header_home">
      <div class="box"> 
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                      {{ message }}
                  </div> 
              {% endfor %}
          {% endif %}
      {% endwith %}
        <h1 style="font-size:px; color:rgb(80, 94, 41)">Welcome to the Carbon App!</span>
        </h1>
        <p style="text-align:center;">
          Thank you for using our app! 
          We developed this app to assist you reducing your carbon footprint. 
          By providing an easy way to calculate your carbon emmisions, you can contribute to the climate change in a positive way. 
          You will gain a better understanding of the factors influencing your carbon footprint and learn actionable steps to decrease it. 
          It is important that governments, businesses and individuals all around the world have a higher focus in decreasing emissions for the greater good. 
          This means gaining a better understanding of  which emissions are a significant contributor to global climate change. In addition, increase the use of renewable energy and adopt low-carbon lifestyles. 
          We hope that our app empowers you to make informed choices, ultimately contributing to the battle against climate change. 
        </p>
        <div class="icons">
          <img 
          src="{{url_for('static', filename='icons/gretat.png')}}"
          style="width: 400px; height: auto;"
          alt=""/>
        </div>
    </div>

      <div class="box logo">
        <img 
          src="{{url_for('static', filename='icons/bilde_logo.png')}}"
          width="400" 
          height="350"
          alt=""/>
      </div>
    </div>

  </div>
</section>   

<!-- Developers -->
<section class="section_developers">
  <div class="container">

    <div class="developers" style="display:block;">
      <h1 style="text-align:center; color: rgb(80, 94, 41) ">Our Team</h1>
      <p style=" text-align: center; color: rgb(80, 94, 41)">
        Our team consist of a diverse group with different backgrounds - we see this as our super power! 
        We are all enrolled in the Master's Program in Entrepreneurship and Innovation at NMBU. 
        Our common ground is that we all share the interest for innovation and sustainability.  
        Meet our team, in the descriptions below. 
        Check out our team below! Each of us brings our own unique experiences and ideas, which helps us solve problems in creative ways. 
        Got any questions? Feel free to hit us up on LinkedIn!
      </p>      
    </div>

   <div class="developers">
        <div class="box">
          <img src="{{url_for('static', filename='icons/IDA.jpeg')}}" alt="" style="border-radius: 50%; width:200px; margin-bottom: 20px;">
          <h3 style=" color:rgb(43, 41, 28)">Ida Hansen Maltun</h3>
          <p style=" text-align: center; font-size: smaller;"> Ida's former education is a Bachelor's degree in media and communication. 
            She is 28 years old, and lives in Oslo.
            She has a strong interest in being more sustainable in terms of buying more used and second hand textiles. 
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="https://www.linkedin.com/in/ida-maltun/"  target="_blank">LinkedIn</a>
          </div>
        </div>
        <div class="box">
          <img src="{{url_for('static', filename='icons/Marie_ok.png')}}" alt="" style="border-radius: 50%; width:200px; margin-bottom: 20px;">
          <h3 style=" color:rgb(43, 41, 28)">Marie Andersson Haug</h3>
          <p style=" text-align: center; font-size: smaller;"> Marie has a bachelor degree in business administration. 
            She is 26 years old, and lives in Oslo. Marie is of the adventure seeking type, always on the look for new and sustainable travel destinations.  
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="https://www.linkedin.com/in/marie-andersson-haug-038649160/"  target="_blank">LinkedIn</a>
          </div> 
        </div>           
        <div class="box">
          <img src="{{url_for('static', filename='icons/SOFIE.jpeg')}}" alt="" style="border-radius: 50%; width:200px; margin-bottom: 20px;">
          <h3 style=" color:rgb(43, 41, 28)">Sofie Skuland</h3>
          <p style=" text-align: center; font-size: smaller;">  Sofie's former education is a Bachelor degree in nursing. 
            She is 27 years old, and lives in Oslo. With Sofie's background we always feel safe and well taken care of. 
            She takes care of the environment the same way she takes care of us - with love and care. 
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="https://www.linkedin.com/in/sofieskuland/"  target="_blank">LinkedIn</a>
          </div> 
        </div>   
        <div class="box2">
          <img src="{{url_for('static', filename='icons/Hannah_ok.png')}}" alt="" style="border-radius: 50%; width:200px; margin-bottom: 20px;">
          <h3 style=" color:rgb(43, 41, 28)">Hannah Bernstein</h3>
          <p style=" text-align: center; font-size: smaller;">  Hannah's former education is a Bachelor degree in marketing and brand management. 
            She is 25 years old, and lives in Ski. Hannah is a strong believer in recycling, and waste management. 
            Maybe someday she will change the way we look at what we today call “waste”. 
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="https://www.linkedin.com/in/hannah-bernstein-542900170/"  target="_blank">LinkedIn</a>
          </div> 
        </div>  
        <div class="box2">
          <img src="{{url_for('static', filename='icons/Eirin_ok.png')}}" alt="" style="border-radius: 50%; width:200px; margin-bottom: 20px;">
          <h3 style=" color:rgb(43, 41, 28)">Eirin Losvik</h3>
          <p style=" text-align: center; font-size: smaller;">  Eirin's former education is a Bachelor degree in criminology. She is 25 years old, born in Finland, but lives in Oslo.
            Eirin is always on the look for new ways of thinking sustainability, improving the world piece by piece. 
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="https://www.linkedin.com/in/eirin-losvik-43407514a/"  target="_blank">LinkedIn</a>
          </div> 
        </div>      
  </div>
  
  </div>          
</section>     
{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

      <!--Import the Bootstrap CSS file:-->
      <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
      />

      <!-- Matjax -->
      <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
      <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

      
      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app_form.css') }}">

      <!--For the plots-->
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>Gruppeoppgave - Carbon App</title>
        {% endif %}

</head>
  <body>
        <section class="section_navbar">
          <div class="container">
            <div class="navbar">
              <div class="logo">
                <img src="{{url_for('static', filename='icons/logo1.png')}}"
                width="180" 
                height="80"
                alt="">
            </div>
              <nav>
                <ul>
                    <li>
                        <a href="{{url_for('home.home_home')}}">
                        <img src="{{url_for('static', filename='icons/home.png')}}" alt="Home Icon"> Home
                      </a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}">
                          <img src="{{url_for('static', filename='icons/information.png')}}" alt="Methodology Icon">Methodology
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}">
                          <img src="{{url_for('static', filename='icons/calculator.png')}}" alt="Carbon App Icon">Carbon App 
                        </a>
                    </li>
                </ul>
              </nav> 
            </div>
          </div>
        </section>
        
        {% block content %} {% endblock %}



        <section class="section_footer">
          <div class="container">
            <div class="footer">
                <a href="{{url_for('home.home_home')}}">
                  <img src="{{url_for('static', filename='icons/logo1.png')}}" alt="Home Icon">
                </a>
            </div>
          </div>
        </section>

        
        <!-- Bootstrap -->
        <!-- Question Accordion -->
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
</html>




capp/templates/methodology.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_methodology">
    <div class="container">
  
      <div class="header">
        <div class="box"> 
            <h1 style="font-size:55px; text-align:center; "><span class="text-logo">Methodology</span></h1>
          <p style="text-align:center;">
            The calculator employs kilometers as its metric unit of measurement and quantifies carbon emissions in terms of CO2. 
            To determine your carbon emissions, it is essential to input the distance in kilometers you cover on a daily, weekly, monthly, or yearly basis.
            For a more in-depth understanding of the methodology and access to our sources, please refer to our scientific paper by clicking the button below.
          <div class="container_buttons_links_header">
            <div class="btn">
                <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(193, 211, 151); border: none;">Paper</a>
            </div>
            <div class="btn">
                <a href="{{url_for('carbon_app.carbon_app_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:rgb(193, 211, 151); border: none;">Carbon App</a>
            </div>
          </div>  
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/methodology.png')}}"
            style="width: 250px; height: auto;"
            alt=""/>
      </div>
      
    </div>
</section> 

<!-- Methodology -->
<section class="section_body_methodology">
    <div class="container">

    <div class="methodology" style="display:block; margin-top: 0; background-color: transparent;">
        <h1 style="text-align:center;"> <br> Our numbers and formulas</h1>
        <p style="text-align:center; margin-left: 40px; margin-right: 40px;">
            Greenhouse gas emissions for various modes of transportation, to provide insight into how the choice of transport can impact the amount of emissions per person are presented below.
            This information are sourced from framtiden.no and are intended to clarify for the user. 
            The carbon app calculator's formulas and methodology are derived by our professor, Mario Blázquez de Paz.
            He gathered the data from the European Environment Agency.
            Our goal with the Carbon App is to heighten awareness regarding individuals' daily carbon footprints within transportation and inspire towards emission reduction.
            <br><br>
            1.	(https://www.framtiden.no/, retrieved 26. November 2023)
            <br>
            2.	(https://efdb.apps.eea.europa.eu/, retrieved 26. November 2023)
            <br>
            <br>
        </p> 
    </div>


        <!--Enumerated list (table with two columns)-->
        <div class="methodology"> 
            <div class="box_table2" style="height:850px;">
                <ol start="1">
                    <li>
                        <h4><strong>Cars</strong></h4>
                        <p class="text-left">
                            <strong>Gasoline:</strong><br>
                            Framtiden.no reports that the average gasoline-powered car emits 63g CO2/km per passenger 

                            <br>
                            <div class="icons">
                                <img 
                                src="{{url_for('static', filename='icons/bensin.png')}}"
                                style="width: 400px; height: auto;"
                                alt=""/>
                            </div>
                        </p>
                        <p class="text-left">
                            Diesel:<br>
                            Framtiden.no reports that the average diesel-powered car emits 54gCO2/km per passenger. 

                            <br>
                            <div class="icons">
                                <img 
                                src="{{url_for('static', filename='icons/diesel.png')}}"
                                style="width: 400px; height: auto;"
                                alt=""/>
                            </div>
                        </p>
                        <p class="text-left">
                            Electric:<br>
                            Framtiden.no reports that the average electrical-powered car consumes 7g CO2/km per passenger

                            <br>
                            <div class="icons">
                                <img 
                                src="{{url_for('static', filename='icons/elektrisk.png')}}"
                                style="width: 400px; height: auto;"
                                alt=""/>
                            </div>
                        </p>
                    </li>
                </ol>                        
            </div>
            <div class="box_table2" style="height:850px;">
                <ol start="2">
                    <li>
                        <h4>Busses</h4>
                        <p class="text-left">
                    
                                Diesel:<br>
                                Framtiden.no reports that the average diesel-powered bus consumes 25g Co2/km per passenger 
                                <br><br>
                                Biodiesel:<br>
                                Framtiden.no reports that the average bio-diesel-powered bus consumes 7g Co2/km per passenger 
                                
                                <div class="icons">
                                    <img 
                                    src="{{url_for('static', filename='icons/buss.png')}}"
                                    style="width: 400px; height: auto;"
                                    alt=""/>
                                  </div>
                        </p>
                    </li>
                </ol>
                <ol start="3">
                    <li>
                        <h4>Airplanes</h4>
                        <p class="text-left">
                            Framtiden.no states that each individual traveling in business class is accountable for emitting 298g of CO2 per kilometer.
                            <br><br>
                            Framtiden.no states that each individual traveling in economy class is accountable for emitting 133g of CO2 per kilometer.
                            <br>
                            <div class="icons">
                                <img 
                                src="{{url_for('static', filename='icons/fly.png')}}"
                                style="width: 400px; height: auto;"
                                alt=""/>
                              </div>
                        </p>
                    </li>
                </ol>
            </div>  
        </div>

        <!--Nederste boks-->
        <div class="methodology">              
            <div class="box_table1">
                      
            </div>
            <div class="box_table1"> 
                        <ol start="4">
                            <li>
                                <h4>Ferrys</h4>
                                <p class="text-left">
                                    According to framtiden.no, each person traveling by ferry is responsible for 266g of CO2 emissions per kilometer.
                                    <br><br>
                                    <div class="icons">
                                        <img 
                                        src="{{url_for('static', filename='icons/ferge.png')}}"
                                        style="width: 400px; height: auto;"
                                        alt=""/>
                                      </div>
                                </p>
                            </li>
                        </ol>
                        <ol start="5">
                            <li>
                                <h4>Train</h4>
                                <p class="text-left">
                                    According to framtiden.no, each person traveling by diesel-powered train is responsible for 91g of CO2 emissions per kilometer. 
                                    Each person travelling with electric train is responsible for 7g of CO2 emissions per kilometer.
                                    <br>
                                    <div class="icons">
                                        <img 
                                        src="{{url_for('static', filename='icons/tog.png')}}"
                                        style="width: 400px; height: auto;"
                                        alt=""/>
                                      </div>                               
                                </p>
                            </li>
                        </ol>
                        <ol start="6">
                            <li>
                                <h4>Bicycling and walking</h4>
                                <p class="text-left">
                                    According to framtiden.no, there are zero emissions per kilometer for individuals cycling or walking.
                                    <br>
                                    <div class="icons">
                                        <img 
                                        src="{{url_for('static', filename='icons/gå.png')}}"
                                        style="width: 400px; height: auto;"
                                        alt=""/>
                                      </div>
                                </p>
                            </li>
                        </ol>
                    </div> 
            <div class="box_table1">
                      
            </div>  
        </div>

        
      
    </div>
</section>

{% endblock content %}